name: build
on:
  push:
    branches:
      - master
  pull_request: 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build docker image
        run: |
              docker build . -t juice-shop:${{ github.sha }}
  cs-scan:
    name: Grype Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Scan
        uses: anchore/scan-action@v6
        with:
          image: bkimminich/juice-shop
          fail-build: false
          output-format: sarif
        id: grype-scan
      - name: Upload Sarif File
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.grype-scan.outputs.sarif}}
      - name: SBOM generate
        uses: anchore/sbom-action@v0
        with:
          image: bkimminich/juice-shop
          output-file: "sbom.spdx.json"
          format: "spdx-json"
  sast-scan:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    container: returntocorp/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Semgrep Scan
        run: semgrep ci --config=auto --sarif --output=semgrep.sarif
        continue-on-error: true
      - name: Upload Sarif File
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
  secret-scan:
    name: Secret Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Scan Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
      continue-on-error: true
      id: gitleaks-scan
    - name: Upload Sarif File
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
  dast-scan:
    name: Dast Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Nuclei - Vulnerability Scan
      id: nuclei_scan
      uses: projectdiscovery/nuclei-action@main
      with:
        target: https://demo.owasp-juice.shop/
    - name: GitHub Workflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuclei.log
        path: nuclei.log
    - name: GitHub Security Dashboard Alerts update
      uses: github/codeql-action/upload-sarif@v3
      if: steps.nuclei_scan.outputs.sarif_exists == 'true'
      with:
        sarif_file: nuclei.sarif
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      

  
        


